### ISSUE TITLE
Error Cannot read property 'tapAsync' of undefined 

### ISSUE THREAD

**Issue by tezine** [ara-framework/webpack-nova-consumer#18]
Hello, I just tried to test the sample provided in  https://ara-framework.github.io/website/blog/2019/09/14/lazy-loading-micro-frontend,  but after editing the nuxt.config.js, whenever I start the nuxt app, I get the following errors below: 

```
 ERROR  Cannot read property 'tapAsync' of undefined                                                                                                                                                                     14:14:18

  at node_modules\@ara\webpack-nova-consumer\index.js:42:61
  at SyncHook.eval [as call] (eval at create (node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:13:1)
  at SyncHook.lazyCompileHook (node_modules\tapable\lib\Hook.js:154:20)
  at Compiler.newCompilation (node_modules\webpack\lib\Compiler.js:631:26)
  at node_modules\webpack\lib\Compiler.js:667:29
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules\tapable\lib\Hook.js:154:20)
  at Compiler.compile (node_modules\webpack\lib\Compiler.js:662:28)
  at node_modules\webpack\lib\Watching.js:77:18
  at _next1 (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
  at eval (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
  at watchRun (node_modules\fork-ts-checker-webpack-plugin\lib\index.js:208:13)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:37:1)
```

The only modification I did was to use typescript instead of javascript. 
Any ideas why this is happening?

**Comment by daniloraisi** [comment]
I'm trying to do the same, but with Javascript. I got the same error under Nuxt.
